// Objective-C API for talking to github.com/fatvpn/fatcore/fatxray Go package.
//   gobind -lang=objc github.com/fatvpn/fatcore/fatxray
//
// File is generated by gobind. Do not edit.

#ifndef __Fatxray_H__
#define __Fatxray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Libbox.objc.h"

@protocol FatxrayProtector;
@class FatxrayProtector;

@protocol FatxrayProtector <NSObject>
- (BOOL)protect:(long)fd;
@end

/**
 * IsRunning reports whether a core is up.
 */
FOUNDATION_EXPORT BOOL FatxrayIsRunning(void);

/**
 * SetProtector installs p for every socket the core opens from now on. Call it
before Start; sockets created earlier are not revisited.

A no-op on platforms whose tunnel already excludes its own sockets — iOS
gives a Network Extension that for free.
 */
FOUNDATION_EXPORT void FatxraySetProtector(id<FatxrayProtector> _Nullable p0);

/**
 * Start brings the core up with configJSON, which must already describe the
local SOCKS inbound sing-box will dial.

Returns an error if a core is already running: the caller is expected to
Stop first, and silently replacing a live core would strand its connections.
 */
FOUNDATION_EXPORT BOOL FatxrayStart(NSString* _Nullable configJSON, NSError* _Nullable* _Nullable error);

/**
 * Stop shuts the core down. Stopping an already-stopped core is not an error,
which keeps teardown paths free of state checks.
 */
FOUNDATION_EXPORT BOOL FatxrayStop(NSError* _Nullable* _Nullable error);

/**
 * Version is the Xray core version, for the support bundle.
 */
FOUNDATION_EXPORT NSString* _Nonnull FatxrayVersion(void);

@class FatxrayProtector;

/**
 * Protector hands a freshly created socket to the platform so it can be kept
out of the tunnel this core is feeding.

Without it the core's own connection to the node enters the tun device,
sing-box routes it back to the core's SOCKS port, and the session deadlocks
on itself.
 */
@interface FatxrayProtector : NSObject <goSeqRefInterface, FatxrayProtector> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)protect:(long)fd;
@end

#endif
