// Objective-C API for talking to github.com/sagernet/sing-box/experimental/libbox Go package.
//   gobind -lang=objc github.com/sagernet/sing-box/experimental/libbox
//
// File is generated by gobind. Do not edit.

#ifndef __Libbox_H__
#define __Libbox_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibboxCommandClient;
@class LibboxCommandClientOptions;
@class LibboxCommandServer;
@class LibboxConnection;
@class LibboxConnectionEvent;
@class LibboxConnectionEvents;
@class LibboxConnectionOwner;
@class LibboxConnections;
@class LibboxDeprecatedNote;
@class LibboxErrorMessage;
@class LibboxExchangeContext;
@class LibboxFDroidMirror;
@class LibboxFDroidPingResult;
@class LibboxFDroidUpdateInfo;
@class LibboxImportRemoteProfile;
@class LibboxLogEntry;
@class LibboxNetworkInterface;
@class LibboxNotification;
@class LibboxOutboundGroup;
@class LibboxOutboundGroupItem;
@class LibboxOverrideOptions;
@class LibboxPProfServer;
@class LibboxProcessInfo;
@class LibboxProfileContent;
@class LibboxProfileContentRequest;
@class LibboxProfileDecoder;
@class LibboxProfileEncoder;
@class LibboxProfilePreview;
@class LibboxRoutePrefix;
@class LibboxSetupOptions;
@class LibboxStatusMessage;
@class LibboxStringBox;
@class LibboxSystemProxyStatus;
@class LibboxWIFIState;
@protocol LibboxCommandClientHandler;
@class LibboxCommandClientHandler;
@protocol LibboxCommandServerHandler;
@class LibboxCommandServerHandler;
@protocol LibboxConnectionEventIterator;
@class LibboxConnectionEventIterator;
@protocol LibboxConnectionIterator;
@class LibboxConnectionIterator;
@protocol LibboxDeprecatedNoteIterator;
@class LibboxDeprecatedNoteIterator;
@protocol LibboxFDroidMirrorIterator;
@class LibboxFDroidMirrorIterator;
@protocol LibboxFDroidPingResultIterator;
@class LibboxFDroidPingResultIterator;
@protocol LibboxFunc;
@class LibboxFunc;
@protocol LibboxHTTPClient;
@class LibboxHTTPClient;
@protocol LibboxHTTPRequest;
@class LibboxHTTPRequest;
@protocol LibboxHTTPResponse;
@class LibboxHTTPResponse;
@protocol LibboxHTTPResponseWriteToProgressHandler;
@class LibboxHTTPResponseWriteToProgressHandler;
@protocol LibboxInt32Iterator;
@class LibboxInt32Iterator;
@protocol LibboxInterfaceUpdateListener;
@class LibboxInterfaceUpdateListener;
@protocol LibboxLocalDNSTransport;
@class LibboxLocalDNSTransport;
@protocol LibboxLogIterator;
@class LibboxLogIterator;
@protocol LibboxNetworkInterfaceIterator;
@class LibboxNetworkInterfaceIterator;
@protocol LibboxOnDemandRule;
@class LibboxOnDemandRule;
@protocol LibboxOnDemandRuleIterator;
@class LibboxOnDemandRuleIterator;
@protocol LibboxOutboundGroupItemIterator;
@class LibboxOutboundGroupItemIterator;
@protocol LibboxOutboundGroupIterator;
@class LibboxOutboundGroupIterator;
@protocol LibboxPlatformInterface;
@class LibboxPlatformInterface;
@protocol LibboxProfilePreviewIterator;
@class LibboxProfilePreviewIterator;
@protocol LibboxRoutePrefixIterator;
@class LibboxRoutePrefixIterator;
@protocol LibboxStringIterator;
@class LibboxStringIterator;
@protocol LibboxTunOptions;
@class LibboxTunOptions;
@protocol LibboxXPCDialer;
@class LibboxXPCDialer;

@protocol LibboxCommandClientHandler <NSObject>
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibboxStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)setDefaultLogLevel:(int32_t)level;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnectionEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)writeGroups:(id<LibboxOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibboxLogIterator> _Nullable)messageList;
- (void)writeStatus:(LibboxStatusMessage* _Nullable)message;
@end

@protocol LibboxCommandServerHandler <NSObject>
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceStop:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)enabled error:(NSError* _Nullable* _Nullable)error;
- (void)writeDebugMessage:(NSString* _Nullable)message;
@end

@protocol LibboxConnectionEventIterator <NSObject>
- (BOOL)hasNext;
- (LibboxConnectionEvent* _Nullable)next;
@end

@protocol LibboxConnectionIterator <NSObject>
- (BOOL)hasNext;
- (LibboxConnection* _Nullable)next;
@end

@protocol LibboxDeprecatedNoteIterator <NSObject>
- (BOOL)hasNext;
- (LibboxDeprecatedNote* _Nullable)next;
@end

@protocol LibboxFDroidMirrorIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidMirror* _Nullable)next;
@end

@protocol LibboxFDroidPingResultIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidPingResult* _Nullable)next;
@end

@protocol LibboxFunc <NSObject>
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxHTTPClient <NSObject>
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibboxHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@protocol LibboxHTTPRequest <NSObject>
- (id<LibboxHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@protocol LibboxHTTPResponse <NSObject>
- (LibboxStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeToWithProgress:(NSString* _Nullable)path handler:(id<LibboxHTTPResponseWriteToProgressHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxHTTPResponseWriteToProgressHandler <NSObject>
- (void)update:(int64_t)progress total:(int64_t)total;
@end

@protocol LibboxInt32Iterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (int32_t)next;
@end

@protocol LibboxInterfaceUpdateListener <NSObject>
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@protocol LibboxLocalDNSTransport <NSObject>
- (BOOL)exchange:(LibboxExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibboxExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@protocol LibboxLogIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxLogEntry* _Nullable)next;
@end

@protocol LibboxNetworkInterfaceIterator <NSObject>
- (BOOL)hasNext;
- (LibboxNetworkInterface* _Nullable)next;
@end

@protocol LibboxOnDemandRule <NSObject>
- (id<LibboxStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibboxStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibboxStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@protocol LibboxOnDemandRuleIterator <NSObject>
- (BOOL)hasNext;
- (id<LibboxOnDemandRule> _Nullable)next;
@end

@protocol LibboxOutboundGroupItemIterator <NSObject>
- (BOOL)hasNext;
- (LibboxOutboundGroupItem* _Nullable)next;
@end

@protocol LibboxOutboundGroupIterator <NSObject>
- (BOOL)hasNext;
- (LibboxOutboundGroup* _Nullable)next;
@end

@protocol LibboxPlatformInterface <NSObject>
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (LibboxConnectionOwner* _Nullable)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (id<LibboxLocalDNSTransport> _Nullable)localDNSTransport;
- (BOOL)openTun:(id<LibboxTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxWIFIState* _Nullable)readWIFIState;
- (BOOL)sendNotification:(LibboxNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)systemCertificates;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)useProcFS;
@end

@protocol LibboxProfilePreviewIterator <NSObject>
- (BOOL)hasNext;
- (LibboxProfilePreview* _Nullable)next;
@end

@protocol LibboxRoutePrefixIterator <NSObject>
- (BOOL)hasNext;
- (LibboxRoutePrefix* _Nullable)next;
@end

@protocol LibboxStringIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@protocol LibboxTunOptions <NSObject>
- (BOOL)getAutoRoute;
- (LibboxStringBox* _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)getExcludePackage;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibboxStringIterator> _Nullable)getIncludePackage;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

@protocol LibboxXPCDialer <NSObject>
- (BOOL)dialXPC:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxCommandClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibboxCommandClientHandler> _Nullable)handler options:(LibboxCommandClientOptions* _Nullable)options;
- (BOOL)clearLogs:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeConnection:(NSString* _Nullable)connId error:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeConnections:(NSError* _Nullable* _Nullable)error;
- (BOOL)connect:(NSError* _Nullable* _Nullable)error;
- (BOOL)connectWithFD:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (BOOL)disconnect:(NSError* _Nullable* _Nullable)error;
- (id<LibboxDeprecatedNoteIterator> _Nullable)getDeprecatedNotes:(NSError* _Nullable* _Nullable)error;
- (BOOL)getStartedAt:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)selectOutbound:(NSString* _Nullable)groupTag outboundTag:(NSString* _Nullable)outboundTag error:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceClose:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)setClashMode:(NSString* _Nullable)newMode error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setGroupExpand:(NSString* _Nullable)groupTag isExpand:(BOOL)isExpand error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)isEnabled error:(NSError* _Nullable* _Nullable)error;
- (BOOL)urlTest:(NSString* _Nullable)groupTag error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxCommandClientOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setStatusInterval:) int64_t statusInterval;
- (void)addCommand:(int32_t)command;
@end

@interface LibboxCommandServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibboxCommandServerHandler> _Nullable)handler platformInterface:(id<LibboxPlatformInterface> _Nullable)platformInterface;
// skipped field CommandServer.StartedService with unsupported type: *github.com/sagernet/sing-box/daemon.StartedService

- (BOOL)checkConfig:(NSString* _Nullable)configContent error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.ClearLogs with unsupported parameter or return types

- (void)close;
// skipped method CommandServer.CloseAllConnections with unsupported parameter or return types

// skipped method CommandServer.CloseConnection with unsupported parameter or return types

- (BOOL)closeService:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)formatConfig:(NSString* _Nullable)configContent error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.GetClashModeStatus with unsupported parameter or return types

// skipped method CommandServer.GetDefaultLogLevel with unsupported parameter or return types

// skipped method CommandServer.GetDeprecatedWarnings with unsupported parameter or return types

// skipped method CommandServer.GetStartedAt with unsupported parameter or return types

// skipped method CommandServer.GetSystemProxyStatus with unsupported parameter or return types

// skipped method CommandServer.Instance with unsupported parameter or return types

- (BOOL)needFindProcess;
- (BOOL)needWIFIState;
- (void)pause;
// skipped method CommandServer.ReloadService with unsupported parameter or return types

- (void)resetNetwork;
// skipped method CommandServer.SelectOutbound with unsupported parameter or return types

// skipped method CommandServer.SetClashMode with unsupported parameter or return types

- (void)setError:(NSString* _Nullable)message;
// skipped method CommandServer.SetGroupExpand with unsupported parameter or return types

// skipped method CommandServer.SetSystemProxyEnabled with unsupported parameter or return types

- (BOOL)start:(NSError* _Nullable* _Nullable)error;
- (BOOL)startOrReloadService:(NSString* _Nullable)configContent options:(LibboxOverrideOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.StopService with unsupported parameter or return types

// skipped method CommandServer.SubscribeClashMode with unsupported parameter or return types

// skipped method CommandServer.SubscribeConnections with unsupported parameter or return types

// skipped method CommandServer.SubscribeGroups with unsupported parameter or return types

// skipped method CommandServer.SubscribeLog with unsupported parameter or return types

// skipped method CommandServer.SubscribeServiceStatus with unsupported parameter or return types

// skipped method CommandServer.SubscribeStatus with unsupported parameter or return types

// skipped method CommandServer.URLTest with unsupported parameter or return types

- (void)updateWIFIState;
- (void)wake;
- (void)writeMessage:(int32_t)level message:(NSString* _Nullable)message;
@end

@interface LibboxConnection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setID:) NSString* _Nonnull id_;
@property (nonatomic, setter=setInbound:) NSString* _Nonnull inbound;
@property (nonatomic, setter=setInboundType:) NSString* _Nonnull inboundType;
@property (nonatomic, setter=setIPVersion:) int32_t ipVersion;
@property (nonatomic, setter=setNetwork:) NSString* _Nonnull network;
@property (nonatomic, setter=setSource:) NSString* _Nonnull source;
@property (nonatomic, setter=setDestination:) NSString* _Nonnull destination;
@property (nonatomic, setter=setDomain:) NSString* _Nonnull domain;
@property (nonatomic, setter=setProtocol:) NSString* _Nonnull protocol;
@property (nonatomic, setter=setUser:) NSString* _Nonnull user;
@property (nonatomic, setter=setFromOutbound:) NSString* _Nonnull fromOutbound;
@property (nonatomic, setter=setCreatedAt:) int64_t createdAt;
@property (nonatomic, setter=setClosedAt:) int64_t closedAt;
@property (nonatomic, setter=setUplink:) int64_t uplink;
@property (nonatomic, setter=setDownlink:) int64_t downlink;
@property (nonatomic, setter=setUplinkTotal:) int64_t uplinkTotal;
@property (nonatomic, setter=setDownlinkTotal:) int64_t downlinkTotal;
@property (nonatomic, setter=setRule:) NSString* _Nonnull rule;
@property (nonatomic, setter=setOutbound:) NSString* _Nonnull outbound;
@property (nonatomic, setter=setOutboundType:) NSString* _Nonnull outboundType;
@property (nonatomic, setter=setProcessInfo:) LibboxProcessInfo* _Nullable processInfo;
- (id<LibboxStringIterator> _Nullable)chain;
- (NSString* _Nonnull)displayDestination;
@end

@interface LibboxConnectionEvent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setID:) NSString* _Nonnull id_;
@property (nonatomic, setter=setConnection:) LibboxConnection* _Nullable connection;
@property (nonatomic, setter=setUplinkDelta:) int64_t uplinkDelta;
@property (nonatomic, setter=setDownlinkDelta:) int64_t downlinkDelta;
@property (nonatomic, setter=setClosedAt:) int64_t closedAt;
@end

@interface LibboxConnectionEvents : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setReset:) BOOL reset;
- (id<LibboxConnectionEventIterator> _Nullable)iterator;
@end

@interface LibboxConnectionOwner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setUserId:) int32_t userId;
@property (nonatomic, setter=setUserName:) NSString* _Nonnull userName;
@property (nonatomic, setter=setProcessPath:) NSString* _Nonnull processPath;
- (id<LibboxStringIterator> _Nullable)androidPackageNames;
- (void)setAndroidPackageNames:(id<LibboxStringIterator> _Nullable)names;
@end

@interface LibboxConnections : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (void)applyEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)filterState:(int32_t)state;
- (id<LibboxConnectionIterator> _Nullable)iterator;
- (void)sortByDate;
- (void)sortByTraffic;
- (void)sortByTrafficTotal;
@end

@interface LibboxDeprecatedNote : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setDescription:) NSString* _Nonnull description;
@property (nonatomic, setter=setDeprecatedVersion:) NSString* _Nonnull deprecatedVersion;
@property (nonatomic, setter=setScheduledVersion:) NSString* _Nonnull scheduledVersion;
@property (nonatomic, setter=setEnvName:) NSString* _Nonnull envName;
@property (nonatomic, setter=setMigrationLink:) NSString* _Nonnull migrationLink;
- (BOOL)impending;
- (NSString* _Nonnull)message;
- (NSString* _Nonnull)messageWithLink;
@end

@interface LibboxErrorMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setMessage:) NSString* _Nonnull message;
- (NSData* _Nullable)encode;
@end

@interface LibboxExchangeContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)errnoCode:(int32_t)code;
- (void)errorCode:(int32_t)code;
- (void)onCancel:(id<LibboxFunc> _Nullable)callback;
- (void)rawSuccess:(NSData* _Nullable)result;
- (void)success:(NSString* _Nullable)result;
@end

@interface LibboxFDroidMirror : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setCountry:) NSString* _Nonnull country;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@end

@interface LibboxFDroidPingResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setLatencyMs:) int32_t latencyMs;
@property (nonatomic, setter=setError:) NSString* _Nonnull error;
@end

@interface LibboxFDroidUpdateInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setVersionCode:) int32_t versionCode;
@property (nonatomic, setter=setVersionName:) NSString* _Nonnull versionName;
@property (nonatomic, setter=setDownloadURL:) NSString* _Nonnull downloadURL;
@property (nonatomic, setter=setFileSize:) int64_t fileSize;
@property (nonatomic, setter=setFileSHA256:) NSString* _Nonnull fileSHA256;
@end

@interface LibboxImportRemoteProfile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setHost:) NSString* _Nonnull host;
@end

@interface LibboxLogEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setLevel:) int32_t level;
@property (nonatomic, setter=setMessage:) NSString* _Nonnull message;
@end

@interface LibboxNetworkInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setIndex:) int32_t index;
@property (nonatomic, setter=setMTU:) int32_t mtu;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setAddresses:) id<LibboxStringIterator> _Nullable addresses;
@property (nonatomic, setter=setFlags:) int32_t flags;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setDNSServer:) id<LibboxStringIterator> _Nullable dnsServer;
@property (nonatomic, setter=setMetered:) BOOL metered;
@end

@interface LibboxNotification : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setIdentifier:) NSString* _Nonnull identifier;
@property (nonatomic, setter=setTypeName:) NSString* _Nonnull typeName;
@property (nonatomic, setter=setTypeID:) int32_t typeID;
@property (nonatomic, setter=setTitle:) NSString* _Nonnull title;
@property (nonatomic, setter=setSubtitle:) NSString* _Nonnull subtitle;
@property (nonatomic, setter=setBody:) NSString* _Nonnull body;
@property (nonatomic, setter=setOpenURL:) NSString* _Nonnull openURL;
@end

@interface LibboxOutboundGroup : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setTag:) NSString* _Nonnull tag;
@property (nonatomic, setter=setType:) NSString* _Nonnull type;
@property (nonatomic, setter=setSelectable:) BOOL selectable;
@property (nonatomic, setter=setSelected:) NSString* _Nonnull selected;
@property (nonatomic, setter=setIsExpand:) BOOL isExpand;
- (id<LibboxOutboundGroupItemIterator> _Nullable)getItems;
@end

@interface LibboxOutboundGroupItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setTag:) NSString* _Nonnull tag;
@property (nonatomic, setter=setType:) NSString* _Nonnull type;
@property (nonatomic, setter=setURLTestTime:) int64_t urlTestTime;
@property (nonatomic, setter=setURLTestDelay:) int32_t urlTestDelay;
@end

@interface LibboxOverrideOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setAutoRedirect:) BOOL autoRedirect;
@property (nonatomic, setter=setIncludePackage:) id<LibboxStringIterator> _Nullable includePackage;
@property (nonatomic, setter=setExcludePackage:) id<LibboxStringIterator> _Nullable excludePackage;
@end

@interface LibboxPProfServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)port;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxProcessInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProcessID:) int64_t processID;
@property (nonatomic, setter=setUserID:) int32_t userID;
@property (nonatomic, setter=setUserName:) NSString* _Nonnull userName;
@property (nonatomic, setter=setProcessPath:) NSString* _Nonnull processPath;
- (id<LibboxStringIterator> _Nullable)packageNames;
@end

@interface LibboxProfileContent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setConfig:) NSString* _Nonnull config;
@property (nonatomic, setter=setRemotePath:) NSString* _Nonnull remotePath;
@property (nonatomic, setter=setAutoUpdate:) BOOL autoUpdate;
@property (nonatomic, setter=setAutoUpdateInterval:) int32_t autoUpdateInterval;
@property (nonatomic, setter=setLastUpdated:) int64_t lastUpdated;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfileContentRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProfileID:) int64_t profileID;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfileDecoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)decode:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxProfilePreviewIterator> _Nullable)iterator;
@end

@interface LibboxProfileEncoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)append:(LibboxProfilePreview* _Nullable)profile;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfilePreview : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProfileID:) int64_t profileID;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setType:) int32_t type;
@end

@interface LibboxRoutePrefix : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)address;
- (NSString* _Nonnull)mask;
- (int32_t)prefix;
- (NSString* _Nonnull)string;
@end

@interface LibboxSetupOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setBasePath:) NSString* _Nonnull basePath;
@property (nonatomic, setter=setWorkingPath:) NSString* _Nonnull workingPath;
@property (nonatomic, setter=setTempPath:) NSString* _Nonnull tempPath;
@property (nonatomic, setter=setFixAndroidStack:) BOOL fixAndroidStack;
@property (nonatomic, setter=setCommandServerListenPort:) int32_t commandServerListenPort;
@property (nonatomic, setter=setCommandServerSecret:) NSString* _Nonnull commandServerSecret;
@property (nonatomic, setter=setLogMaxLines:) long logMaxLines;
@property (nonatomic, setter=setDebug:) BOOL debug;
@end

@interface LibboxStatusMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setMemory:) int64_t memory;
@property (nonatomic, setter=setGoroutines:) int32_t goroutines;
@property (nonatomic, setter=setConnectionsIn:) int32_t connectionsIn;
@property (nonatomic, setter=setConnectionsOut:) int32_t connectionsOut;
@property (nonatomic, setter=setTrafficAvailable:) BOOL trafficAvailable;
@property (nonatomic, setter=setUplink:) int64_t uplink;
@property (nonatomic, setter=setDownlink:) int64_t downlink;
@property (nonatomic, setter=setUplinkTotal:) int64_t uplinkTotal;
@property (nonatomic, setter=setDownlinkTotal:) int64_t downlinkTotal;
@end

@interface LibboxStringBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setValue:) NSString* _Nonnull value;
@end

@interface LibboxSystemProxyStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setAvailable:) BOOL available;
@property (nonatomic, setter=setEnabled:) BOOL enabled;
@end

@interface LibboxWIFIState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)wifiSSID wifiBSSID:(NSString* _Nullable)wifiBSSID;
@property (nonatomic, setter=setSSID:) NSString* _Nonnull ssid;
@property (nonatomic, setter=setBSSID:) NSString* _Nonnull bssid;
@end

FOUNDATION_EXPORT const int32_t LibboxCommandClashMode;
FOUNDATION_EXPORT const int32_t LibboxCommandConnections;
FOUNDATION_EXPORT const int32_t LibboxCommandGroup;
FOUNDATION_EXPORT const int32_t LibboxCommandLog;
FOUNDATION_EXPORT const int32_t LibboxCommandStatus;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventClosed;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventNew;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventUpdate;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateActive;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateAll;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateClosed;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeCellular;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeEthernet;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeOther;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeWIFI;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeError;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileContent;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileContentRequest;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileList;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeLocal;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeRemote;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeiCloud;

FOUNDATION_EXPORT BOOL LibboxAvailablePort(int32_t startPort, int32_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL LibboxCheckConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxFDroidUpdateInfo* _Nullable LibboxCheckFDroidUpdate(NSString* _Nullable mirrorURL, NSString* _Nullable packageName, int32_t currentVersionCode, NSString* _Nullable cachePath, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL LibboxCompareSemver(NSString* _Nullable left, NSString* _Nullable right);

FOUNDATION_EXPORT LibboxErrorMessage* _Nullable LibboxDecodeErrorMessage(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT int32_t LibboxDecodeLengthChunk(NSData* _Nullable data);

FOUNDATION_EXPORT LibboxProfileContent* _Nullable LibboxDecodeProfileContent(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxProfileContentRequest* _Nullable LibboxDecodeProfileContentRequest(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable LibboxEncodeChunkedMessage(NSData* _Nullable data);

FOUNDATION_EXPORT LibboxConnectionOwner* _Nullable LibboxFindConnectionOwner(int32_t ipProtocol, NSString* _Nullable sourceAddress, int32_t sourcePort, NSString* _Nullable destinationAddress, int32_t destinationPort, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatBytes(int64_t length);

FOUNDATION_EXPORT LibboxStringBox* _Nullable LibboxFormatConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatDuration(int64_t duration);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatMemoryBytes(int64_t length);

FOUNDATION_EXPORT NSString* _Nonnull LibboxGenerateRemoteProfileImportLink(NSString* _Nullable name, NSString* _Nullable remoteURL);

FOUNDATION_EXPORT id<LibboxFDroidMirrorIterator> _Nullable LibboxGetFDroidMirrors(void);

FOUNDATION_EXPORT int32_t LibboxGetTunnelFileDescriptor(void);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewCommandClient(id<LibboxCommandClientHandler> _Nullable handler, LibboxCommandClientOptions* _Nullable options);

FOUNDATION_EXPORT LibboxCommandServer* _Nullable LibboxNewCommandServer(id<LibboxCommandServerHandler> _Nullable handler, id<LibboxPlatformInterface> _Nullable platformInterface, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxConnections* _Nullable LibboxNewConnections(void);

FOUNDATION_EXPORT id<LibboxHTTPClient> _Nullable LibboxNewHTTPClient(void);

FOUNDATION_EXPORT LibboxPProfServer* _Nullable LibboxNewPProfServer(long port);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewStandaloneCommandClient(void);

FOUNDATION_EXPORT LibboxWIFIState* _Nullable LibboxNewWIFIState(NSString* _Nullable wifiSSID, NSString* _Nullable wifiBSSID);

FOUNDATION_EXPORT LibboxImportRemoteProfile* _Nullable LibboxParseRemoteProfileImportLink(NSString* _Nullable importLink, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxFDroidPingResult* _Nullable LibboxPingFDroidMirror(NSString* _Nullable mirrorURL);

FOUNDATION_EXPORT id<LibboxFDroidPingResultIterator> _Nullable LibboxPingFDroidMirrors(NSString* _Nullable mirrorURLs, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxProxyDisplayType(NSString* _Nullable proxyType);

FOUNDATION_EXPORT LibboxStringBox* _Nullable LibboxRandomHex(int32_t length);

FOUNDATION_EXPORT BOOL LibboxRedirectStderr(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibboxSetLocale(NSString* _Nullable localeId);

FOUNDATION_EXPORT void LibboxSetMemoryLimit(BOOL enabled);

FOUNDATION_EXPORT void LibboxSetXPCDialer(id<LibboxXPCDialer> _Nullable dialer);

FOUNDATION_EXPORT BOOL LibboxSetup(LibboxSetupOptions* _Nullable options, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxVersion(void);

@class LibboxCommandClientHandler;

@class LibboxCommandServerHandler;

@class LibboxConnectionEventIterator;

@class LibboxConnectionIterator;

@class LibboxDeprecatedNoteIterator;

@class LibboxFDroidMirrorIterator;

@class LibboxFDroidPingResultIterator;

@class LibboxFunc;

@class LibboxHTTPClient;

@class LibboxHTTPRequest;

@class LibboxHTTPResponse;

@class LibboxHTTPResponseWriteToProgressHandler;

@class LibboxInt32Iterator;

@class LibboxInterfaceUpdateListener;

@class LibboxLocalDNSTransport;

@class LibboxLogIterator;

@class LibboxNetworkInterfaceIterator;

@class LibboxOnDemandRule;

@class LibboxOnDemandRuleIterator;

@class LibboxOutboundGroupItemIterator;

@class LibboxOutboundGroupIterator;

@class LibboxPlatformInterface;

@class LibboxProfilePreviewIterator;

@class LibboxRoutePrefixIterator;

@class LibboxStringIterator;

@class LibboxTunOptions;

@class LibboxXPCDialer;

@interface LibboxCommandClientHandler : NSObject <goSeqRefInterface, LibboxCommandClientHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibboxStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)setDefaultLogLevel:(int32_t)level;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnectionEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)writeGroups:(id<LibboxOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibboxLogIterator> _Nullable)messageList;
- (void)writeStatus:(LibboxStatusMessage* _Nullable)message;
@end

@interface LibboxCommandServerHandler : NSObject <goSeqRefInterface, LibboxCommandServerHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceStop:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)enabled error:(NSError* _Nullable* _Nullable)error;
- (void)writeDebugMessage:(NSString* _Nullable)message;
@end

@interface LibboxConnectionEventIterator : NSObject <goSeqRefInterface, LibboxConnectionEventIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxConnectionEvent* _Nullable)next;
@end

@interface LibboxConnectionIterator : NSObject <goSeqRefInterface, LibboxConnectionIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxConnection* _Nullable)next;
@end

@interface LibboxDeprecatedNoteIterator : NSObject <goSeqRefInterface, LibboxDeprecatedNoteIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxDeprecatedNote* _Nullable)next;
@end

@interface LibboxFDroidMirrorIterator : NSObject <goSeqRefInterface, LibboxFDroidMirrorIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidMirror* _Nullable)next;
@end

@interface LibboxFDroidPingResultIterator : NSObject <goSeqRefInterface, LibboxFDroidPingResultIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidPingResult* _Nullable)next;
@end

@interface LibboxFunc : NSObject <goSeqRefInterface, LibboxFunc> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxHTTPClient : NSObject <goSeqRefInterface, LibboxHTTPClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibboxHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@interface LibboxHTTPRequest : NSObject <goSeqRefInterface, LibboxHTTPRequest> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibboxHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@interface LibboxHTTPResponse : NSObject <goSeqRefInterface, LibboxHTTPResponse> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibboxStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeToWithProgress:(NSString* _Nullable)path handler:(id<LibboxHTTPResponseWriteToProgressHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxHTTPResponseWriteToProgressHandler : NSObject <goSeqRefInterface, LibboxHTTPResponseWriteToProgressHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)update:(int64_t)progress total:(int64_t)total;
@end

@interface LibboxInt32Iterator : NSObject <goSeqRefInterface, LibboxInt32Iterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (int32_t)next;
@end

@interface LibboxInterfaceUpdateListener : NSObject <goSeqRefInterface, LibboxInterfaceUpdateListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@interface LibboxLocalDNSTransport : NSObject <goSeqRefInterface, LibboxLocalDNSTransport> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)exchange:(LibboxExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibboxExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@interface LibboxLogIterator : NSObject <goSeqRefInterface, LibboxLogIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxLogEntry* _Nullable)next;
@end

@interface LibboxNetworkInterfaceIterator : NSObject <goSeqRefInterface, LibboxNetworkInterfaceIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxNetworkInterface* _Nullable)next;
@end

@interface LibboxOnDemandRule : NSObject <goSeqRefInterface, LibboxOnDemandRule> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibboxStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibboxStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibboxStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@interface LibboxOnDemandRuleIterator : NSObject <goSeqRefInterface, LibboxOnDemandRuleIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (id<LibboxOnDemandRule> _Nullable)next;
@end

@interface LibboxOutboundGroupItemIterator : NSObject <goSeqRefInterface, LibboxOutboundGroupItemIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxOutboundGroupItem* _Nullable)next;
@end

@interface LibboxOutboundGroupIterator : NSObject <goSeqRefInterface, LibboxOutboundGroupIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxOutboundGroup* _Nullable)next;
@end

@interface LibboxPlatformInterface : NSObject <goSeqRefInterface, LibboxPlatformInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (LibboxConnectionOwner* _Nullable)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (id<LibboxLocalDNSTransport> _Nullable)localDNSTransport;
- (BOOL)openTun:(id<LibboxTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxWIFIState* _Nullable)readWIFIState;
- (BOOL)sendNotification:(LibboxNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)systemCertificates;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)useProcFS;
@end

@interface LibboxProfilePreviewIterator : NSObject <goSeqRefInterface, LibboxProfilePreviewIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxProfilePreview* _Nullable)next;
@end

@interface LibboxRoutePrefixIterator : NSObject <goSeqRefInterface, LibboxRoutePrefixIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxRoutePrefix* _Nullable)next;
@end

@interface LibboxStringIterator : NSObject <goSeqRefInterface, LibboxStringIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@interface LibboxTunOptions : NSObject <goSeqRefInterface, LibboxTunOptions> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)getAutoRoute;
- (LibboxStringBox* _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)getExcludePackage;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibboxStringIterator> _Nullable)getIncludePackage;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

@interface LibboxXPCDialer : NSObject <goSeqRefInterface, LibboxXPCDialer> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)dialXPC:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

#endif
