
// Objective-C API for talking to the following Go packages
//
//	github.com/sagernet/sing-box/experimental/libbox
//	github.com/fatvpn/fatcore/fatxray
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libbox_FRAMEWORK_H__
#define __Libbox_FRAMEWORK_H__

#include "Libbox.objc.h"
#include "Fatxray.objc.h"
#include "Universe.objc.h"

#endif
